default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:db, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>

development:
  <<: *default
  database: chef_app

test:
  <<: *default
  database: chef_app_test

production:
  <<: *default
  database: chef_app
