source "https://api.berkshelf.com"

cookbook 'chef_hostname', '~> 0.6.1'
cookbook 'users', '~> 5.3.1'
cookbook 'sudo', '~> 4.0.0'
cookbook 'postgresql_lwrp', '~> 1.2.1'
cookbook 'locale', '~> 2.0.1'
cookbook 'chef_rvm', '~> 2.0.0'
cookbook 'nodejs', '~> 5.0.0'
cookbook 'imagemagick', '~> 0.2.3'
cookbook 'redis', git: 'git://github.com/phlipper/chef-redis.git'
cookbook 'nginx', '~> 7.0.2'
cookbook 'openssh', '~> 2.6.1'
cookbook 'monit', '~> 1.0.0'
